### ISSUE TITLE
关于全隔离地址空间访问用户态内存的效率问题

### ISSUE THREAD

**Issue by jwnhy** [HUST-OS/tornado-os#36]
您好，在博客上拜读了你们关于全隔离地址空间的设计，感觉比较有意思。

但有一件事让我比较好奇，全隔离地址空间的情况下，内核态访问用户态内存无法利用 TLB 等方式加速。

使得每次访问都需要执行多次访存操作，这样是否带来了比较大的性能开销？

**Comment by SKTT1Ryze** [comment]
您好，谢谢您的 issue!
关于您说的问题，在全隔离地址空间的设计下，我们获得了比较好的安全性，但同时也确实牺牲了一定的性能。
在这种设计下，内核访问用户态地址空间需要多次页表翻译，确实带来多次访存的开销。
但对于这种开销，我们针对于某个具体场景是可以进行优化的。
比如常见的读写文件场景，内核需要向用户态的地址空间的某个缓冲区读写数据，在这种场景下我们可以在内核空间留一块虚拟空间，这块空间虚拟地址到物理地址的映射关系是和用户缓冲区虚拟地址到物理地址的映射是相同的。这样就使得内核页表和用户态页表有一些相同的页表项，这些页表项是关于用户态缓冲区虚拟地址到物理地址的映射的。
当内核态拿到用户缓冲区的虚拟地址的时候，直接去访问内存，如果产生缺页异常，则在中断处理函数里面访问用户态页表查相应的页表项，并将其写到内核页表里面，再去访问用户缓冲区的虚拟地址。下一次内核再访问这个缓冲区的时候，就可以通过 TLB 加速了。
可能对于您说的这种性能开销，在特定场景下我们可以通过其他办法来减少。谢谢。

**Comment by jwnhy** [comment]
谢谢您的解答。
